// // // import { Geist, Geist_Mono } from "next/font/google";
// // // import "./globals.css";

// // // const geistSans = Geist({
// // //   variable: "--font-geist-sans",
// // //   subsets: ["latin"],
// // // });

// // // const geistMono = Geist_Mono({
// // //   variable: "--font-geist-mono",
// // //   subsets: ["latin"],
// // // });

// // // export const metadata = {
// // //   title: "Create Next App",
// // //   description: "Generated by create next app",
// // // };

// // // export default function RootLayout({ children }) {
// // //   return (
// // //     <html lang="en">
// // //       <body className={`${geistSans.variable} ${geistMono.variable}`}>
// // //         {children}
// // //       </body>
// // //     </html>
// // //   );
// // // }



// // import React from 'react';
// // import Navbar from '../components/Navbar';
// // // import Footer from '../components/Footer';
// // import './globals.css';

// // export const metadata = {
// //   title: 'Matrimonial App',
// //   description: 'Find your perfect match',
// // };

// // export default function RootLayout({ children }) {
// //   return (
// //     <html lang="en">
// //       <body>
// //         <Navbar />
// //         <main>{children}</main>
// //         {/* <Footer /> */}
// //       </body>
// //     </html>
// //   );
// // }



// 'use client';

// import React from 'react';
// import Navbar from '../components/Navbar';

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <head />
//       <body>
//         <Navbar />
//         {/* Add padding to prevent content overlap */}
//         <div style={{ paddingTop: '50px' }}>{children}</div>
//       </body>
//     </html>
//   );
// }




'use client';

import React from 'react';
import Navbar from '../components/Navbar';

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <head>
        <title>Document</title>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <script src="https://kit.fontawesome.com/628c8d2499.js" crossOrigin="anonymous"></script>
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet" />
        <link rel="stylesheet" href="/style.css" type="text/css" />
      </head>
      <body>
      <Navbar />
        {children}
      </body>
    </html>
  );
}
